<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="client_serveur" nsURI="http://www.example.org/client_serveur"
    nsPrefix="cs">
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="cosa.ecore#//Composant"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPC" eSuperTypes="cosa.ecore#//Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur" lowerBound="1"
        eType="#//Serveur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client_serveur" eSuperTypes="cosa.ecore#//Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" upperBound="-1"
        eType="#//Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rpc" upperBound="-1" eType="#//RPC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur" upperBound="-1"
        eType="#//Serveur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serveur" eSuperTypes="cosa.ecore#//Element_Architectural"/>
</ecore:EPackage>
