<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="client_serveur" nsURI="http://www.example.org/client_serveur"
    nsPrefix="cs">
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="cosa.ecore#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_client" upperBound="-1"
        eType="#//Interface_Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPC" eSuperTypes="cosa.ecore#//Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_rpc" upperBound="-1"
        eType="#//Interface_RPC" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client_serveur" eSuperTypes="cosa.ecore#//Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" upperBound="-1"
        eType="#//Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rpc" upperBound="-1" eType="#//RPC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur" upperBound="-1"
        eType="#//Serveur_Comp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Client">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_client" upperBound="-1"
        eType="#//Port_Fourni_Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_client" upperBound="-1"
        eType="#//Port_Requis_Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_RPC" eSuperTypes="cosa.ecore#//Interface_Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_rpc_client"
        upperBound="-1" eType="#//Role_Fourni_RPC_Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_rpc_client"
        upperBound="-1" eType="#//Role_Requis_RPC_Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_rpc_serveur"
        upperBound="-1" eType="#//Role_Fourni_RPC_Serveur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_rpc_serveur"
        upperBound="-1" eType="#//Role_Requis_RPC_Serveur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataBase" eSuperTypes="cosa.ecore#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_database" upperBound="-1"
        eType="#//Interface_DataBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_DataBase" eSuperTypes="cosa.ecore#//Interface_Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_db_gamma" upperBound="-1"
        eType="#//Port_Fourni_DB_Gamma" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_gamma_db" upperBound="-1"
        eType="#//Port_Requis_Gamma_DB" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_db_beta" upperBound="-1"
        eType="#//Port_Fourni_DB_Beta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_beta_db" upperBound="-1"
        eType="#//Port_Requis_Beta_DB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serveur_Comp" eSuperTypes="cosa.ecore#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_serveur_comp"
        upperBound="-1" eType="#//Interface_Serveur_Comp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur_conf" upperBound="-1"
        eType="#//Serveur_Conf" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Serveur_Comp" eSuperTypes="cosa.ecore#//Interface_Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_serveur" upperBound="-1"
        eType="#//Port_Requis_Serveur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_serveur" upperBound="-1"
        eType="#//Port_Fourni_Serveur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Serveur_Conf" eSuperTypes="cosa.ecore#//Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" upperBound="-1"
        eType="#//DataBase" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security_manager" upperBound="-1"
        eType="#//Security_Manager" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection_manager" upperBound="-1"
        eType="#//Connection_Manager" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gamma" upperBound="-1"
        eType="#//Gamma" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alpha" upperBound="-1"
        eType="#//Alpha" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beta" upperBound="-1" eType="#//Beta"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Serveur" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_rpc_serveur"
        eType="#//Attachment_RPC_Serveur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_Serveur" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachement_serveur_rpc"
        eType="#//Attachement_Serveur_RPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_RPC_Client" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_client_rpc"
        eType="#//Attachment_Client_RPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_RPC_Client" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_rpc_client"
        eType="#//Attachment_RPC_Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Client" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_rpc_client"
        eType="#//Attachment_RPC_Client"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_Client" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_client_rpc"
        eType="#//Attachment_Client_RPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Client_RPC" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_RPC_Client" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_RPC_Serveur" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachement_serveur_rpc"
        eType="#//Attachement_Serveur_RPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_RPC_Serveur" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_rpc_serveur"
        eType="#//Attachment_RPC_Serveur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_RPC_Serveur" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachement_Serveur_RPC" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Security_Manager" eSuperTypes="cosa.ecore#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_security_manager"
        upperBound="-1" eType="#//Interface_Security_Manager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection_Manager" eSuperTypes="cosa.ecore#//Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_connection_manager"
        upperBound="-1" eType="#//Interface_Connection_Manager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Connection_Manager" eSuperTypes="cosa.ecore#//Interface_Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_cm_gamma" upperBound="-1"
        eType="#//Port_Fourni_CM_Gamma" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_gamma_cm" upperBound="-1"
        eType="#//Port_Requis_Gamma_CM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_cm_alpha" upperBound="-1"
        eType="#//Port_Fourni_CM_Alpha" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_alpha_cm" upperBound="-1"
        eType="#//Port_Requis_Alpha_CM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Security_Manager" eSuperTypes="cosa.ecore#//Interface_Composant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_sm_beta" upperBound="-1"
        eType="#//Port_Fourni_SM_Beta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_beta_sm" upperBound="-1"
        eType="#//Port_Requis_Beta_SM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_fourni_sm_alpha" upperBound="-1"
        eType="#//Port_Fourni_SM_Alpha" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port_requis_alpha_sm" upperBound="-1"
        eType="#//Port_Requis_Alpha_SM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Alpha_CM" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_alpha_cm" eType="#//Attachment_Alpha_CM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_CM_Alpha" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_cm_alpha" eType="#//Attachment_CM_Alpha"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_CM_Gamma" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_cm_gamma" eType="#//Attachment_CM_Gamma"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Gamma_CM" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_gamma_cm" eType="#//Attachment_Gamma_CM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_DB_Gamma" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_db_gamma" eType="#//Attachment_DB_Gamma"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Gamma_DB" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_gamma_db" eType="#//Attachment_Gamma_DB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_DB_Beta" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_db_beta" eType="#//Attachment_DB_Beta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Beta_DB" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_beta_db" eType="#//Attachment_Beta_DB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_SM_Alpha" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_sm_alpha" eType="#//Attachment_SM_Alpha"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Alpha_SM" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_alpha_sm" eType="#//Attachment_Alpha_SM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Fourni_SM_Beta" eSuperTypes="cosa.ecore#//Port_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_sm_beta" eType="#//Attachment_SM_Beta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port_Requis_Beta_SM" eSuperTypes="cosa.ecore#//Port_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_beta_sm" eType="#//Attachment_Beta_SM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Beta" eSuperTypes="cosa.ecore#//Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_beta" upperBound="-1"
        eType="#//Interface_Beta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alpha" eSuperTypes="cosa.ecore#//Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_alpha" upperBound="-1"
        eType="#//Interface_Alpha" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gamma" eSuperTypes="cosa.ecore#//Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface_gamma" upperBound="-1"
        eType="#//Interface_Gamma" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Beta" eSuperTypes="cosa.ecore#//Interface_Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_beta_sm" upperBound="-1"
        eType="#//Role_Fourni_Beta_SM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_sm_beta" upperBound="-1"
        eType="#//Role_Requis_SM_Beta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_db_beta" upperBound="-1"
        eType="#//Role_Requis_DB_Beta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_beta_db" upperBound="-1"
        eType="#//Role_Fourni_Beta_DB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Alpha" eSuperTypes="cosa.ecore#//Interface_Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_alpha_sm" upperBound="-1"
        eType="#//Role_Fourni_Alpha_SM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_sm_alpha" upperBound="-1"
        eType="#//Role_Requis_SM_Alpha" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_cm_alpha" upperBound="-1"
        eType="#//Role_Requis_CM_Alpha" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_alpha_cm" upperBound="-1"
        eType="#//Role_Fourni_Alpha_CM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface_Gamma" eSuperTypes="cosa.ecore#//Interface_Connecteur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_cm_gamma" upperBound="-1"
        eType="#//Role_Requis_CM_Gamma" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_gamma_cm" upperBound="-1"
        eType="#//Role_Fourni_Gamma_CM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_requis_db_gamma" upperBound="-1"
        eType="#//Role_Requis_DB_Gamma" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role_fourni_gamma_db" upperBound="-1"
        eType="#//Role_Fourni_Gamma_DB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_SM_Beta" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_sm_beta" eType="#//Attachment_SM_Beta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Beta_SM" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_beta_sm" eType="#//Attachment_Beta_SM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_DB_Beta" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_db_beta" eType="#//Attachment_DB_Beta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Beta_DB" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_beta_db" eType="#//Attachment_Beta_DB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Gamma_CM" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_gamma_cm" eType="#//Attachment_Gamma_CM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_CM_Gamma" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_cm_gamma" eType="#//Attachment_CM_Gamma"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_DB_Gamma" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_db_gamma" eType="#//Attachment_DB_Gamma"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Gamma_DB" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_gamma_db" eType="#//Attachment_Gamma_DB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_SM_Alpha" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_sm_alpha" eType="#//Attachment_SM_Alpha"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Alpha_SM" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_alpha_sm" eType="#//Attachment_Alpha_SM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Requis_CM_Alpha" eSuperTypes="cosa.ecore#//Role_Requis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_cm_alpha" eType="#//Attachment_CM_Alpha"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role_Fourni_Alpha_CM" eSuperTypes="cosa.ecore#//Role_Fourni">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment_alpha_cm" eType="#//Attachment_Alpha_CM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_SM_Alpha" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Alpha_SM" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_CM_Alpha" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Alpha_CM" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_SM_Beta" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Beta_SM" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_DB_Beta" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Beta_DB" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_CM_Gamma" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Gamma_CM" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_DB_Gamma" eSuperTypes="cosa.ecore#//Attachment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment_Gamma_DB" eSuperTypes="cosa.ecore#//Attachment"/>
</ecore:EPackage>
